# Generated by Django 4.2.21 on 2025-06-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deputy_registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EventSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultyservices.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='EventsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=256)),
                ('event_name', models.TextField()),
                ('bodies', models.TextField()),
                ('event_type', models.CharField(max_length=250)),
                ('event_sub_type', models.CharField(max_length=250)),
                ('event_remark', models.TextField(blank=True, null=True)),
                ('hod_remark', models.TextField(blank=True, null=True)),
                ('dean_remark', models.TextField(blank=True, null=True)),
                ('audience_type', models.CharField(max_length=250)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('timeslot', models.CharField(blank=True, max_length=50, null=True)),
                ('event_description', models.TextField()),
                ('coordinator1', models.CharField(blank=True, max_length=250, null=True)),
                ('coordinator2', models.CharField(blank=True, max_length=250, null=True)),
                ('coordinator3', models.CharField(blank=True, max_length=250, null=True)),
                ('coordinator4', models.CharField(blank=True, max_length=250, null=True)),
                ('coordinator5', models.CharField(blank=True, max_length=250, null=True)),
                ('resource_person1', models.TextField(blank=True, null=True)),
                ('resource_person2', models.TextField(blank=True, null=True)),
                ('resource_person3', models.TextField(blank=True, null=True)),
                ('resource_person4', models.TextField(blank=True, null=True)),
                ('resource_person5', models.TextField(blank=True, null=True)),
                ('resource_person6', models.TextField(blank=True, null=True)),
                ('resource_person7', models.TextField(blank=True, null=True)),
                ('resource_person8', models.TextField(blank=True, null=True)),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='events/proposals')),
                ('vcapproval_file', models.FileField(blank=True, null=True, upload_to='events/approvals')),
                ('vcapproval_status', models.CharField(blank=True, max_length=50, null=True)),
                ('hodapproval_status', models.CharField(blank=True, max_length=50, null=True)),
                ('deanapproval_status', models.CharField(blank=True, max_length=50, null=True)),
                ('creatives', models.FileField(blank=True, null=True, upload_to='events/creatives')),
                ('attendance_file', models.FileField(blank=True, null=True, upload_to='events/attendance')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='events/reports')),
                ('geotagpics_file1', models.FileField(blank=True, null=True, upload_to='events/geotagpics')),
                ('geotagpics_file2', models.FileField(blank=True, null=True, upload_to='events/geotagpics')),
                ('geotagpics_file3', models.FileField(blank=True, null=True, upload_to='events/geotagpics')),
                ('news_social_media', models.FileField(blank=True, null=True, upload_to='events/socialmedia')),
                ('news_print_media', models.FileField(blank=True, null=True, upload_to='events/printmedia')),
                ('videoclip', models.URLField(blank=True, null=True)),
                ('values_and_attributes', models.TextField(blank=True, null=True)),
                ('upload_by', models.CharField(max_length=256)),
                ('event_budget', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount_spent', models.CharField(blank=True, max_length=20, null=True)),
                ('event_venue', models.TextField(blank=True, null=True)),
                ('event_outcomes', models.TextField(blank=True, null=True)),
                ('report_text', models.TextField(blank=True, null=True)),
                ('backdrop', models.CharField(blank=True, max_length=256, null=True)),
                ('standee', models.CharField(blank=True, max_length=100, null=True)),
                ('creative', models.CharField(blank=True, max_length=300, null=True)),
                ('certificate', models.CharField(blank=True, max_length=300, null=True)),
                ('other_requirements', models.TextField(blank=True, null=True)),
                ('members', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deputy_registrar.school')),
            ],
        ),
    ]
