# Generated by Django 4.2.21 on 2025-06-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('medical_leave', models.DecimalField(decimal_places=1, default=12.0, max_digits=5)),
                ('compensatory_leave', models.DecimalField(decimal_places=1, default=8.0, max_digits=5)),
                ('earned_leave', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('semester_leave', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
                ('maternity_leave', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('paternity_leave', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('extraordinary_leave', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('academic_leave', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
                ('half_pay_leave', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
                ('duty_leave', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('hpl', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
                ('vacation_leave', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('casual_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('medical_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('compensatory_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('earned_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('semester_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('maternity_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('paternity_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('extraordinary_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('academic_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('half_pay_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('duty_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('hpl_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('vacation_leave_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('compensatory', 'Compensatory Leave'), ('semester', 'Semester Break'), ('half_pay', 'Half Pay Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('earned', 'Earned Leave'), ('extraordinary', 'Extraordinary Leave'), ('academic', 'Academic Leave'), ('duty', 'Duty Leave')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_of_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.TextField()),
                ('contact_during_leave', models.CharField(max_length=15)),
                ('address_during_leave', models.TextField(blank=True, null=True)),
                ('forward_to', models.CharField(max_length=100)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('forwarded_to_hr', 'Forwarded to HR'), ('approved_by_hr', 'Approved by HR'), ('rejected_by_hr', 'Rejected by HR'), ('forwarded_to_hod', 'Forwarded to HOD'), ('approved_by_hod', 'Approved by HOD'), ('rejected_by_hod', 'Rejected by HOD'), ('forwarded_to_dean', 'Forwarded to Dean'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('forwarded_to_vc', 'Forwarded to VC'), ('approved_by_vc', 'Approved by VC'), ('rejected_by_vc', 'Rejected by VC')], default='pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('class_timing', models.CharField(max_length=50)),
                ('concerned_teacher', models.CharField(max_length=100)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_adjustments', to='leave_management.leaveapplication')),
            ],
        ),
    ]
