# Generated by Django 4.2.21 on 2025-07-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='cl_slot1_lapsed',
            field=models.BooleanField(default=False, help_text='Has Slot 1 CL lapsed?'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='cl_slot1_total',
            field=models.DecimalField(decimal_places=1, default=7.0, help_text='Max CL in Slot 1 (Jan-Dec)', max_digits=4),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='cl_slot1_used',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='CL used in Slot 1 (Jan-Dec)', max_digits=4),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='cl_slot2_lapsed',
            field=models.BooleanField(default=False, help_text='Has Slot 2 CL lapsed?'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='cl_slot2_total',
            field=models.DecimalField(decimal_places=1, default=8.0, help_text='Max CL in Slot 2 (Jul-Jun)', max_digits=4),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='cl_slot2_used',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='CL used in Slot 2 (Jul-Jun)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.DecimalField(decimal_places=1, default=15.0, help_text='[LEGACY] Use cl_slot1_total and cl_slot2_total instead.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave_used',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='[LEGACY] Use cl_slot1_used and cl_slot2_used instead.', max_digits=5),
        ),
    ]
