# Generated by Django 4.2.21 on 2025-06-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=70, null=True)),
                ('branch', models.CharField(blank=True, max_length=70, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('SemesterWise', 'Semester Wise'), ('YearWise', 'Year Wise')], default='SemesterWise', max_length=20)),
                ('system_type', models.CharField(choices=[('GradingWise', 'Grading Wise'), ('PercentageWise', 'Percentage Wise')], default='GradingWise', max_length=20)),
                ('education_level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('Diploma', 'Diploma'), ('PG_Diploma', 'PG Diploma'), ('PhD', 'PhD')], default='UG', max_length=20)),
                ('regulatory_bodies', models.CharField(choices=[('AICTE', 'AICTE'), ('INC', 'INC'), ('PCI', 'PCI'), ('ICAR', 'ICAR'), ('NCT', 'NCT')], default='AICTE', max_length=20)),
                ('nep_non_nep', models.CharField(choices=[('NEP', 'NEP'), ('Non-NEP', 'Non-NEP')], default='Non-NEP', max_length=20)),
                ('naac_non_naac', models.CharField(choices=[('NAAC', 'NAAC'), ('Non-NAAC', 'Non-NAAC')], default='NAAC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deputy_registrar.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('academic_year', 'course', 'branch', 'semester', 'school')},
            },
        ),
    ]
