# Generated by Django 4.2.21 on 2025-06-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deputy_registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=20)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deputy_registrar.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm1', models.IntegerField()),
                ('midterm2', models.IntegerField()),
                ('class_participation', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('endterm_theory', models.IntegerField()),
                ('endterm_practical', models.IntegerField()),
                ('internal_viva', models.IntegerField()),
                ('progressive', models.IntegerField(blank=True, default=0, null=True)),
                ('total_practical_credits', models.IntegerField()),
                ('total_tutorial_credits', models.IntegerField()),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('introduction_year', models.CharField(blank=True, max_length=4, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='deputy_registrar.subject')),
            ],
        ),
    ]
