# Generated by Django 4.2.21 on 2025-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='faculty/profile_images/'),
        ),
    ]
