# Generated by Django 4.2.21 on 2025-07-04 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_faculty_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Educational Certificates', 'Educational Certificates'), ('Experience Certificates', 'Experience Certificates'), ('Research Publications', 'Research Publications')], max_length=50)),
                ('file', models.FileField(upload_to='faculty/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
