# Generated by Django 4.2.21 on 2025-07-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_facultydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='faculty',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mother_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
